# HTTP Listener Configuration
http.port=8081
http.host=localhost

# Environment-specific configuration
config.resources=local.yaml

# OAuth 2.0 Configuration References
oauth.auth0.client_secret=XiHNlNLnDfijsYQMBHt_DKtG7CYVdKD6G2lkZ7hqfUSYay7dYpBT9PHV5tUem6Tm