# HTTP Listener Configuration
http.port=8081
http.host=localhost

# TD FDX resource server (no path suffix; e.g. https://your-app.region.cloudhub.io)
td.resource_server.base_url=https://ob-td-fdx-app-fomag7.f5od7g.usa-e2.cloudhub.io

# Environment-specific configuration
config.resources=local.yaml

# OAuth 2.0 Configuration References
oauth.auth0.client_secret=XiHNlNLnDfijsYQMBHt_DKtG7CYVdKD6G2lkZ7hqfUSYay7dYpBT9PHV5tUem6Tm